### ISSUE TITLE
Prompt for submission directory and file names 

### ISSUE THREAD

**Issue by ccnadude** [ayalac1111/GradeIt#4]
"Enter the path to the files:"
"Enter the path to the csv file that contains the student usernames:"
"Enter the path to the the answer file:"

This could also eliminate the feature of using arguments for individual submissions. If the "students.csv" file can be anywhere with any name, the user can just make another file with just one username.

**Comment by ayalac1111** [comment]
The issue regarding prompting for submission directories and filenames has been addressed in this commit 754128941d7e38c69b8bbf4d27d9db8def40e340 

The script now uses a `config.yaml` file that gives users full control over directory and file paths, eliminating the need for prompts. 

You can define the exact paths for submissions, feedback, and other files directly in the `config.yaml` file, allowing for a more flexible and streamlined workflow.

**Comment by ccnadude** [comment]
Do you hate idea of prompting for the files and directories?

**Comment by ayalac1111** [comment]
Added  user interaction to define paths and files in this commit 495b41e58809370c420fbb54dfb6f5bb4f7448b4
